//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public decimal ACCOUNT_ID { get; set; }
        public decimal BRANCH_ID { get; set; }
        public decimal CUSTOMER_ID { get; set; }
        public string ACCOUNT_NUMBER { get; set; }
        public string ACCOUNT_TYPE { get; set; }
        public decimal BALANCE { get; set; }
        public string ACCOUNT_STATUS { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual BRANCH BRANCH { get; set; }
    }
}
