//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bank_Management_System_Entities : DbContext
    {
        public Bank_Management_System_Entities()
            : base("name=Bank_Management_System_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCOUNT> ACCOUNTS { get; set; }
        public DbSet<BRANCH> BRANCHes { get; set; }
        public DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public DbSet<LOAN> LOANs { get; set; }
        public DbSet<TRANSACTION> TRANSACTIONS { get; set; }
        public DbSet<VERIFYEMPLOYEE> VERIFYEMPLOYEEs { get; set; }
    }
}
