//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCH
    {
        public BRANCH()
        {
            this.ACCOUNTS = new HashSet<ACCOUNT>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.CUSTOMERs = new HashSet<CUSTOMER>();
            this.TRANSACTIONS = new HashSet<TRANSACTION>();
            this.LOANs = new HashSet<LOAN>();
        }
    
        public decimal BRANCH_ID { get; set; }
        public string BRANCH_NAME { get; set; }
        public string BRANCH_MANAGER_NAME { get; set; }
        public string BRANCH_MANAGER_EMAIL { get; set; }
        public string BRANCH_MANAGER_PASSWORD { get; set; }
        public Nullable<System.DateTime> BRANCH_MANAGER_JOINDATE { get; set; }
        public string BRANCH_CITY { get; set; }
        public string BRANCH_COUNTRY { get; set; }
        public string BRANCH_PHONE { get; set; }
        public string BRANCH_MANAGER_PICTURE { get; set; }
    
        public virtual ICollection<ACCOUNT> ACCOUNTS { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
        public virtual ICollection<TRANSACTION> TRANSACTIONS { get; set; }
        public virtual ICollection<LOAN> LOANs { get; set; }
    }
}
