//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
        }
    
        public decimal DEPARTMENT_ID { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string HEAD_OF_DEPARTMENT { get; set; }
    
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
    }
}
