//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.VERIFYEMPLOYEEs = new HashSet<VERIFYEMPLOYEE>();
            this.TRANSACTIONS = new HashSet<TRANSACTION>();
            this.LOANs = new HashSet<LOAN>();
        }
    
        public decimal EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string EMPLOYEE_EMAIL { get; set; }
        public string EMPLOYEE_PASSWORD { get; set; }
        public string EMPLOYEE_PHONE { get; set; }
        public Nullable<System.DateTime> EMPLOYEE_JOINDATE { get; set; }
        public decimal BRANCH_ID { get; set; }
        public decimal DEPARTMENT_ID { get; set; }
        public string EMPLOYEE_ADDRESS { get; set; }
        public string EMPLOYEE_PICTURE { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<VERIFYEMPLOYEE> VERIFYEMPLOYEEs { get; set; }
        public virtual ICollection<TRANSACTION> TRANSACTIONS { get; set; }
        public virtual ICollection<LOAN> LOANs { get; set; }
    }
}
