//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN
    {
        public decimal LOAN_ID { get; set; }
        public decimal BRANCH_ID { get; set; }
        public decimal CUSTOMER_ID { get; set; }
        public decimal ACCOUNT_ID { get; set; }
        public decimal EMPLOYEE_ID { get; set; }
        public long LOAN_AMMOUNT { get; set; }
        public decimal INTEREST_RATE { get; set; }
        public decimal DURATIONS { get; set; }
        public System.DateTime START_DATE { get; set; }
        public decimal DUE_AMMOUNT { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
