//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public decimal TRANSACTIONS_ID { get; set; }
        public decimal BRANCH_ID { get; set; }
        public decimal CUSTOMER_ID { get; set; }
        public decimal ACCOUNT_ID { get; set; }
        public decimal EMPLOYEE_ID { get; set; }
        public string CREDITEORDEPOSIT { get; set; }
        public long AMMOUNT { get; set; }
        public string TRANSACTIONS_TYPE { get; set; }
        public Nullable<System.DateTime> DATETIMESTAMP { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
